name: example-environment
channels:
  - conda-forge
  - damianavila82
dependencies:
  - python
  - rise
  - nbconvert=5.4.1
  - pip:
    - numpy
    - matplotlib
    - pandas
    - scipy
    - pynverse
